version: '3'
services:
  my_module_dev:
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    container_name: my_module_dev
    image: dagster_dev_image
    entrypoint:
      - dagster
      - dev
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    tty: true